'use client';
import type { Metadata } from "next";
import { ThemeProvider } from "styled-components";
import defaultTheme from "@/styles/themes/default.theme";
import "./globals.css";
import localFont from 'next/font/local'


const proxyMono = localFont({

  src: [{
    path: '../fonts/ProxyMono-Regular.otf',
    weight: '400',
    style: 'normal',
  },
  {
    path: '../fonts/ProxyMono-Light.otf',
    weight: '300',
    style: 'normal',
  },
],
  display: 'swap',
  variable: '--font-proxymono',
});


const proxyNeo = localFont({
  src: [{
    path: '../fonts/ProxyNeo-Regular.otf',
    weight: '400',
    style: 'normal',
  },
  {
    path: '../fonts/ProxyNeo-Bold.otf',
    weight: '700',
    style: 'normal',
  },
],
  display: 'swap',
  variable: '--font-proxyneo',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={proxyMono.className + ' ' + proxyNeo.className}>
      <body>
        <ThemeProvider theme={defaultTheme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
